name: stepup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  email_validator: ^3.0.0
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.1
  firebase_database: ^11.0.1
  firebase_storage: ^12.0.1
  flutter_native_splash: ^2.4.0
  logger: ^2.3.0
  provider: ^6.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    